---
- hosts: all
  become: true
  roles:
  - ui
  - comment
  pre_tasks:
    - name: clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /opt/reddit
        version: microservices_for_mc
